#Puerto donde correr� el backend
server.port=${PORT:8080}

#Tu clave secreta de prueba de Stripe (Empieza por sk_test_...)
stripe.api.key=${STRIPE_API_KEY}

#URL de tu Realtime Database
firebase.database.url=${FIREBASE_DB_URL}

#Secreto del Webhook de Stripe (lo obtendremos con Stripe CLI)
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory